### ISSUE TITLE
Error calculating word pieces for sentences with XLM

### ISSUE THREAD

**Issue by severinsimmler** [explosion/spacy-transformers#54] opened 2019-09-03 17:06 UTC
Thank you for this great package!

Unfortunately I get the following `ValueError` (the BERT example from the README works just fine):

```python
>>> name = "xlm-mlm-ende-1024"
>>> nlp = PyTT_Language(pytt_name=name, meta={"lang": "en"})
>>> nlp.add_pipe(nlp.create_pipe("sentencizer"))
>>> nlp.add_pipe(PyTT_WordPiecer.from_pretrained(nlp.vocab, name))
>>> nlp.add_pipe(PyTT_TokenVectorEncoder.from_pretrained(nlp.vocab, name))
>>> nlp("This is a document.")
Using eos_token, but it is not set yet.
["'This'", "'is'", "'a'", "'document'", "'.'"]
['<s>', 'this</w>', 'is</w>', 'a</w>', 'document</w>', '.</w>']
This [1]
is [2]
a [3]
document [4, 5]
. []
['<s>', 'this</w>', 'is</w>', 'a</w>', 'document</w>', '.</w>', None]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simmler/.local/share/virtualenvs/pytorch-8keEDJZg/lib/python3.7/site-packages/spacy/language.py", line 402, in __call__
    doc = proc(doc, **component_cfg.get(name, {}))
  File "/home/simmler/.local/share/virtualenvs/pytorch-8keEDJZg/lib/python3.7/site-packages/spacy_pytorch_transformers/pipeline/wordpiecer.py", line 51, in __call__
    self.set_annotations([doc], pieces)
  File "/home/simmler/.local/share/virtualenvs/pytorch-8keEDJZg/lib/python3.7/site-packages/spacy_pytorch_transformers/pipeline/wordpiecer.py", line 155, in set_annotations
    f"Error calculating word pieces for sentences. Total number "
ValueError: Error calculating word pieces for sentences. Total number of wordpieces in the doc was 7, but adding up the wordpieces for its sentences we get 6. This means there's a bug in the extension attributes or the tokenizer.add_special_tokens() logic, often when a spaCy sentence aligns against 0 wordpieces.
```

- Python 3.7.3
- `spacy` 2.1.8
- `spacy-pytorch-transformers` 0.3.0
- `pytorch-transformers` 1.1.0

**Comment by talk2dfox** [comment] 2020-06-12 01:34
I'm seeing the same problem when calling nlp, with either the BERT or ROBERTA en_trf, so I think this is generic to spacy-transformers, and not specific to which en_trf model.  However, I'm having some odd issues reproducing the problem.  It will fail to create a document from a particular, fairly long string.  Then I try other ways of preprocessing the string or shorter variants and they don't give an error.  Then when I try the first string, it succeeds.

For right now, I'm under a project deadline, so I've gone back to using the spacy en_vectors_web_lg embedding instead.  If I have time next week, I'll try to reduce this to a simple reproducible case.

I'm using Python 3.6.8, spacy 2.2.4, spacy-transformers 0.5.2.

**Comment by adrianeboyd** [comment] 2020-06-12 08:00
@talk2dfox: I think this is a separate issue that is a duplicate of #193. If you're interested, you can try installing from source to test the fix (this will be released as v0.5.3 soon):

```
pip install https://github.com/explosion/spacy-transformers/archive/v0.5.x.zip
```

Feedback is appreciated if you run into any errors!

**Comment by talk2dfox** [comment] 2020-06-13 01:12
That does seem to fix the problem in my case.  Thanks.

David

**Comment by adrianeboyd** [comment] 2020-06-13 10:03
Glad to hear it worked!

**Comment by svlandeg** [comment] 2021-02-01 11:12
This library has been significantly rewritten and published today as v. 1.0. We'll publish the corresponding spaCy v. 3.0 very soon as well 🥳 

It would be great if you could retry your previous scripts and let us know how you go on the [spaCy discussions forum](https://github.com/explosion/spaCy/discussions). Bugs can be posted on the [spaCy GitHub tracker](https://github.com/explosion/spaCy/issues). 

Thanks for testing the early prereleases of this package! All the feedback has been really helpful :-)

**Closed by svlandeg** 2021-02-01 11:12 UTC
Labels: bug
